# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
    ]
